"""Lê um diff unificado e separa arquivos, trechos e o que não será revisado."""

import posixpath
import re
from dataclasses import dataclass
from typing import Literal

from agent_sample.domain.model import EmptyDiff, InvalidDiff, Unreviewed

FileStatus = Literal["added", "modified", "deleted", "renamed"]
LineKind = Literal["+", "-", " "]

HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")
GIT_HEADER = re.compile(r"^diff --git a/(.+?) b/(.+)$")

LANGUAGES: dict[str, str] = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".java": "java",
    ".kt": "kotlin",
    ".rb": "ruby",
    ".rs": "rust",
    ".cs": "csharp",
    ".php": "php",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".sh": "shell",
    ".sql": "sql",
    ".md": "docs",
    ".rst": "docs",
    ".txt": "docs",
    ".adoc": "docs",
    ".yml": "config",
    ".yaml": "config",
    ".json": "config",
    ".toml": "config",
    ".ini": "config",
    ".cfg": "config",
}
NON_CODE = frozenset({"docs", "config", "unknown"})

GENERATED_NAMES = frozenset(
    {
        "uv.lock",
        "poetry.lock",
        "Pipfile.lock",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Cargo.lock",
        "go.sum",
        "composer.lock",
        "Gemfile.lock",
    }
)
GENERATED_SUFFIXES = (".min.js", ".min.css", "_pb2.py", "_pb2_grpc.py", ".pb.go", ".map")
GENERATED_MARKERS = ("@generated", "do not edit", "auto-generated", "autogenerated")


@dataclass(frozen=True, slots=True)
class DiffLine:
    kind: LineKind
    text: str
    new_line: int | None


@dataclass(frozen=True, slots=True)
class Hunk:
    old_start: int
    new_start: int
    lines: tuple[DiffLine, ...]


@dataclass(frozen=True, slots=True)
class FileChange:
    path: str
    old_path: str | None
    status: FileStatus
    binary: bool
    hunks: tuple[Hunk, ...]

    @property
    def language(self) -> str:
        return language_of(self.path)

    @property
    def is_code(self) -> bool:
        return self.language not in NON_CODE

    @property
    def is_test(self) -> bool:
        return is_test_path(self.path)

    @property
    def added(self) -> tuple[DiffLine, ...]:
        return tuple(line for hunk in self.hunks for line in hunk.lines if line.kind == "+")

    @property
    def size(self) -> int:
        return sum(1 for hunk in self.hunks for line in hunk.lines if line.kind != " ")

    def has_new_line(self, number: int) -> bool:
        """A linha existe no código novo e aparece no diff (adicionada ou de contexto)."""
        return any(
            line.new_line == number
            for hunk in self.hunks
            for line in hunk.lines
            if line.kind != "-"
        )

    def contains(self, snippet: str) -> bool:
        """Toda linha não vazia do trecho aparece em alguma linha do diff deste arquivo."""
        wanted = [_squash(_unprefix(line)) for line in snippet.splitlines()]
        wanted = [line for line in wanted if line]
        if not wanted:
            return False
        present = [_squash(line.text) for hunk in self.hunks for line in hunk.lines]
        return all(any(want in line for line in present) for want in wanted)


@dataclass(frozen=True, slots=True)
class ChangeSet:
    files: tuple[FileChange, ...]
    unreviewed: tuple[Unreviewed, ...]

    @property
    def paths(self) -> tuple[str, ...]:
        return tuple(file.path for file in self.files)

    @property
    def languages(self) -> tuple[str, ...]:
        return tuple(sorted({file.language for file in self.files if file.is_code}))

    def file(self, path: str) -> FileChange | None:
        for file in self.files:
            if file.path == path:
                return file
        return None


def language_of(path: str) -> str:
    name = posixpath.basename(path)
    if name in GENERATED_NAMES:
        return "config"
    return LANGUAGES.get(posixpath.splitext(name)[1].lower(), "unknown")


def is_test_path(path: str) -> bool:
    name = posixpath.basename(path)
    parts = path.split("/")[:-1]
    if any(part in ("test", "tests", "__tests__", "spec") for part in parts):
        return True
    stem = posixpath.splitext(name)[0]
    return (
        stem.startswith("test_")
        or stem.endswith(("_test", "_spec", ".test", ".spec"))
        or stem.startswith("Test")
        or stem.endswith("Test")
    )


def parse_diff(text: str) -> tuple[FileChange, ...]:
    """Transforma um diff unificado (formato git ou clássico) em arquivos e trechos."""
    if not text.strip():
        raise EmptyDiff()
    lines = text.splitlines()
    files: list[FileChange] = []
    index = 0
    while index < len(lines):
        if lines[index].startswith("diff --git ") or _starts_classic(lines, index):
            file, index = _parse_file(lines, index)
            files.append(file)
        else:
            index += 1
    if not files:
        raise InvalidDiff("no file headers found")
    return tuple(files)


def normalize(files: tuple[FileChange, ...], max_file_lines: int) -> ChangeSet:
    """Separa o que será revisado do que não será, sempre com o motivo."""
    reviewable: list[FileChange] = []
    unreviewed: list[Unreviewed] = []
    for file in files:
        reason = _skip_reason(file, max_file_lines)
        if reason is None:
            reviewable.append(file)
        else:
            unreviewed.append(Unreviewed(file.path, reason))
    return ChangeSet(tuple(reviewable), tuple(unreviewed))


def _skip_reason(file: FileChange, max_file_lines: int) -> str | None:
    if file.binary:
        return "binary file"
    if file.status == "deleted":
        return "file deleted"
    if _generated(file):
        return "generated file"
    if file.size > max_file_lines:
        return f"too large ({file.size} changed lines > {max_file_lines})"
    if not file.added:
        return "renamed without changes" if file.status == "renamed" else "only removed lines"
    return None


def _generated(file: FileChange) -> bool:
    name = posixpath.basename(file.path)
    if name in GENERATED_NAMES or name.endswith(GENERATED_SUFFIXES):
        return True
    head = " ".join(line.text.lower() for line in file.added[:5])
    return any(marker in head for marker in GENERATED_MARKERS)


def _starts_classic(lines: list[str], index: int) -> bool:
    return (
        lines[index].startswith("--- ")
        and index + 1 < len(lines)
        and lines[index + 1].startswith("+++ ")
    )


def _parse_file(lines: list[str], index: int) -> tuple[FileChange, int]:
    old_path: str | None = None
    new_path: str | None = None
    status: FileStatus = "modified"
    binary = False
    if lines[index].startswith("diff --git "):
        matched = GIT_HEADER.match(lines[index])
        if matched is None:
            raise InvalidDiff(f"bad header: {lines[index]}")
        old_path, new_path = matched.group(1), matched.group(2)
        index += 1
        while index < len(lines) and not lines[index].startswith(("--- ", "@@", "diff --git ")):
            line = lines[index]
            if line.startswith("new file mode"):
                status = "added"
            elif line.startswith("deleted file mode"):
                status = "deleted"
            elif line.startswith("rename from "):
                status = "renamed"
                old_path = line.removeprefix("rename from ")
            elif line.startswith("rename to "):
                new_path = line.removeprefix("rename to ")
            elif line.startswith("Binary files ") or line.startswith("GIT binary patch"):
                binary = True
            index += 1
    if index < len(lines) and lines[index].startswith("--- "):
        if index + 1 >= len(lines) or not lines[index + 1].startswith("+++ "):
            raise InvalidDiff(f"'---' without '+++' at line {index + 1}")
        old = _header_path(lines[index][4:])
        new = _header_path(lines[index + 1][4:])
        if old is None:
            status = "added"
        if new is None:
            status = "deleted"
        old_path = old or old_path
        new_path = new or new_path or old
        index += 2
    if new_path is None:
        raise InvalidDiff("file without a path")
    hunks: list[Hunk] = []
    while index < len(lines) and lines[index].startswith("@@"):
        hunk, index = _parse_hunk(lines, index)
        hunks.append(hunk)
    path = old_path if status == "deleted" and old_path else new_path
    renamed_from = old_path if old_path != path else None
    return FileChange(path, renamed_from, status, binary, tuple(hunks)), index


def _parse_hunk(lines: list[str], index: int) -> tuple[Hunk, int]:
    matched = HUNK.match(lines[index])
    if matched is None:
        raise InvalidDiff(f"bad hunk header: {lines[index]}")
    old_start, new_start = int(matched.group(1)), int(matched.group(3))
    old_left = int(matched.group(2) or 1)
    new_left = int(matched.group(4) or 1)
    index += 1
    parsed: list[DiffLine] = []
    new_number = new_start
    while index < len(lines) and (old_left > 0 or new_left > 0):
        line = lines[index]
        if line.startswith("\\"):
            index += 1
            continue
        marker, text = (line[:1] or " "), line[1:]
        if marker == "+":
            parsed.append(DiffLine("+", text, new_number))
            new_number += 1
            new_left -= 1
        elif marker == "-":
            parsed.append(DiffLine("-", text, None))
            old_left -= 1
        elif marker == " ":
            parsed.append(DiffLine(" ", text, new_number))
            new_number += 1
            new_left -= 1
            old_left -= 1
        else:
            raise InvalidDiff(f"unexpected line in hunk: {line[:40]}")
        index += 1
    if old_left > 0 or new_left > 0:
        raise InvalidDiff("hunk ended before its declared length")
    while index < len(lines) and lines[index].startswith("\\"):
        index += 1
    return Hunk(old_start, new_start, tuple(parsed)), index


def _header_path(raw: str) -> str | None:
    path = raw.split("\t")[0].strip()
    if path == "/dev/null":
        return None
    if path.startswith(("a/", "b/")):
        return path[2:]
    return path


def _unprefix(line: str) -> str:
    return line[1:] if line[:1] in ("+", "-") else line


def _squash(text: str) -> str:
    return " ".join(text.split())
